apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fileserver-claim
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: slow
  volumeName: fileserver
  resources:
    requests:
      storage: 8T