apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-tcga-worker-clone
spec:
  storageClassName: csi-storageclass
  dataSource:
    name: pv-claim-tcga-worker
    kind: PersistentVolumeClaim
    apiGroup: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi # NOTE this capacity must be specified and must be >= the capacity of the source volume